apiVersion: v2
name: neo-cpp
description: A Helm chart for deploying Neo C++ blockchain nodes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - neo
  - blockchain
  - distributed-ledger
home: https://github.com/neo-project/neo-cpp
sources:
  - https://github.com/neo-project/neo-cpp
maintainers:
  - name: Neo Project
    email: dev@neo.org
icon: https://neo.org/images/neo-logo.png
annotations:
  category: Blockchain