apiVersion: v1
kind: ConfigMap
metadata:
  name: neo-config
  namespace: neo-cpp
data:
  neo.json: |
    {
      "ApplicationConfiguration": {
        "Logger": {
          "Path": "/data/logs",
          "ConsoleOutput": true,
          "Level": "info"
        },
        "Storage": {
          "Engine": "RocksDB",
          "Path": "/data/chain"
        },
        "P2P": {
          "Port": 10333,
          "MaxConnections": 100,
          "MinDesiredConnections": 10
        },
        "RPC": {
          "Port": 10332,
          "Enabled": true,
          "MaxConcurrentConnections": 100,
          "MaxGasInvoke": 10000000
        },
        "UnlockWallet": {
          "Path": "",
          "Password": "",
          "IsActive": false
        }
      },
      "ProtocolConfiguration": {
        "Network": "mainnet",
        "Magic": 5195086,
        "MillisecondsPerBlock": 15000,
        "MaxTraceableBlocks": 2102400,
        "InitialGasDistribution": 52000000,
        "MaxTransactionsPerBlock": 512,
        "MemoryPoolMaxTransactions": 50000,
        "MaxIteratorResultItems": 100,
        "StandbyCommittee": [],
        "SeedList": [
          "seed1.neo.org:10333",
          "seed2.neo.org:10333",
          "seed3.neo.org:10333",
          "seed4.neo.org:10333",
          "seed5.neo.org:10333"
        ]
      }
    }
  mainnet.json: |
    {
      "network": "mainnet",
      "magic": 5195086,
      "port": 10333,
      "seedList": [
        "seed1.neo.org:10333",
        "seed2.neo.org:10333",
        "seed3.neo.org:10333"
      ]
    }
  testnet.json: |
    {
      "network": "testnet",
      "magic": 1951352142,
      "port": 20333,
      "seedList": [
        "seed1.testnet.neo.org:20333",
        "seed2.testnet.neo.org:20333",
        "seed3.testnet.neo.org:20333"
      ]
    }