var searchData=
[
  ['immediate_0',['Phase 1 (Immediate)',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md236',1,'']]],
  ['immediate_20actions_1',['Immediate Actions',['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md23',1,'']]],
  ['impact_20analysis_2',['Missing Features Impact Analysis',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md222',1,'']]],
  ['impact_20can_20be_20added_20later_3',['Low Impact (Can be added later)',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md223',1,'']]],
  ['implementation_4',['&lt;b&gt;✅ COMPLETE IMPLEMENTATION&lt;/b&gt;',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md173',1,'']]],
  ['implementation_5',['Implementation',['../md__t_e_s_t___i_m_p_l_e_m_e_n_t_a_t_i_o_n___g_u_i_d_e.html#autotoc_md455',1,'Critical Test Modules That Need Implementation'],['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md344',1,'dBFT Implementation'],['../md__r_e_a_d_m_e.html',1,'Neo C++ - Professional Neo N3 Blockchain Implementation'],['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md354',1,'Neo VM Implementation']]],
  ['implementation_20✅_6',['Implementation ✅',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md336',1,'1. Protocol Implementation ✅'],['../md__f_i_n_a_l___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md245',1,'2. P2P Block Request Implementation ✅'],['../md__f_i_n_a_l___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md246',1,'3. Block Processing Implementation ✅']]],
  ['implementation_20compatibility_20report_7',['Neo N3 C++ Implementation Compatibility Report',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html',1,'']]],
  ['implementation_20details_8',['3. Implementation Details',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md365',1,'']]],
  ['implementation_20final_20delivery_20summary_9',['Neo C++ Implementation - Final Delivery Summary',['../md__f_i_n_a_l___d_e_l_i_v_e_r_y___s_u_m_m_a_r_y.html',1,'']]],
  ['implementation_20guide_10',['Neo C++ Test Implementation Guide',['../md__t_e_s_t___i_m_p_l_e_m_e_n_t_a_t_i_o_n___g_u_i_d_e.html',1,'']]],
  ['implementation_20priority_11',['Implementation Priority',['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html#autotoc_md417',1,'']]],
  ['implementation_20quality_12',['Implementation Quality',['../md_code__analysis__report.html#autotoc_md84',1,'']]],
  ['implementation_20status_13',['Implementation Status',['../md__r_e_a_d_m_e.html#autotoc_md423',1,'']]],
  ['implementation_20summary_14',['Neo C++ Implementation Summary',['../md__i_m_p_l_e_m_e_n_t_a_t_i_o_n___s_u_m_m_a_r_y.html',1,'']]],
  ['implementation_20testing_15',['Cross-Implementation Testing',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md361',1,'']]],
  ['implementation_20verification_16',['Implementation Verification',['../md__t_e_s_t___r_e_s_u_l_t_s.html#autotoc_md470',1,'']]],
  ['implementation_20working_17',['⏸️ TIMEOUT TESTS (Implementation Working)',['../md__n_e_w___i_n_t_e_g_r_a_t_i_o_n___t_e_s_t___r_e_s_u_l_t_s.html#autotoc_md382',1,'']]],
  ['implementation_3a_18',['Excellent Implementation:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md281',1,'']]],
  ['implementations_20previously_20thought_20missing_19',['✅ CONFIRMED IMPLEMENTATIONS (Previously Thought Missing)',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md202',1,'']]],
  ['implemented_20',['IMPLEMENTED',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md204',1,'2. <b>Consensus Recovery - IMPLEMENTED</b>'],['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md205',1,'3. <b>NEP-17 RPC Methods - IMPLEMENTED</b>']]],
  ['implemented_20block_20storage_20✅_21',['3. Implemented Block Storage ✅',['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html#autotoc_md405',1,'']]],
  ['implemented_20c_20compatible_20_3a_22',['Implemented C Compatible :',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md276',1,'Implemented (C# Compatible):'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md280',1,'Implemented (C# Compatible):'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md283',1,'Implemented (C# Compatible):'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md286',1,'Implemented (C# Compatible):'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md290',1,'Implemented (C# Compatible):'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md293',1,'Implemented (C# Compatible):'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md302',1,'Implemented (C# Compatible):']]],
  ['implemented_20capabilities_23',['Implemented Capabilities',['../md__i_m_p_l_e_m_e_n_t_a_t_i_o_n___s_u_m_m_a_r_y.html#autotoc_md256',1,'']]],
  ['implemented_20methods_24',['Implemented Methods',['../md_code__analysis__report.html#autotoc_md54',1,'']]],
  ['implemented_20methods_3a_25',['Implemented Methods:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md307',1,'']]],
  ['implemented_20patterns_26',['Well-Implemented Patterns',['../md_code__analysis__report.html#autotoc_md77',1,'']]],
  ['implemented_3a_27',['Implemented:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md296',1,'Implemented:'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md299',1,'Implemented:'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md304',1,'Implemented:'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md310',1,'Implemented:']]],
  ['important_20_3a_28',['Priority 2 (Important):',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md318',1,'']]],
  ['improvement_20⚠️_29',['Areas for Improvement ⚠️',['../md_code__analysis__report.html#autotoc_md40',1,'']]],
  ['improvements_30',['Improvements',['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html#autotoc_md413',1,'6. Caching Improvements'],['../md__c_o_m_p_a_t_i_b_i_l_i_t_y___f_i_x_e_s___s_u_m_m_a_r_y.html#autotoc_md110',1,'Architecture Improvements'],['../md__c_o_m_p_a_t_i_b_i_l_i_t_y___f_i_x_e_s___s_u_m_m_a_r_y.html#autotoc_md114',1,'Code Quality Improvements'],['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md19',1,'Expected Performance Improvements'],['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md24',1,'Recommended Improvements']]],
  ['improvements_20vs_20c_20neo_31',['Benchmarked Improvements (vs C# Neo)',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md214',1,'']]],
  ['include_20neo_20core_20neo_5fsystem_20h_32',['3. &lt;span class=&quot;tt&quot;&gt;include/neo/core/neo_system.h&lt;/span&gt;',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md393',1,'']]],
  ['incomplete_20test_20modules_33',['Incomplete Test Modules',['../md__t_e_s_t___i_m_p_l_e_m_e_n_t_a_t_i_o_n___g_u_i_d_e.html#autotoc_md456',1,'']]],
  ['information_34',['Version Information',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md375',1,'']]],
  ['input_20validation_20✅_35',['Input Validation ✅',['../md_code__analysis__report.html#autotoc_md69',1,'']]],
  ['instructions_36',['🚀 &lt;b&gt;Deployment Instructions&lt;/b&gt;',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md155',1,'']]],
  ['integration_20flow_20verified_37',['Integration Flow Verified',['../md__f_i_n_a_l___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md251',1,'']]],
  ['integration_20points_20✅_38',['4. Integration Points ✅',['../md__f_i_n_a_l___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md247',1,'']]],
  ['integration_20test_20results_39',['New Integration Test Results',['../md__n_e_w___i_n_t_e_g_r_a_t_i_o_n___t_e_s_t___r_e_s_u_l_t_s.html',1,'']]],
  ['integration_20testing_20results_40',['Integration Testing Results',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md220',1,'Integration Testing Results'],['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md360',1,'Integration Testing Results']]],
  ['intentional_41',['Known Differences (Intentional)',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md362',1,'']]],
  ['interface_20✅_42',['7. RPC Interface ✅',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md349',1,'']]],
  ['interops_3a_43',['Missing Interops:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md294',1,'']]],
  ['io_20module_20neo_3a_3aio_44',['1. IO Module (neo::io)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md275',1,'']]],
  ['is_20ready_45',['✅ &lt;b&gt;VERIFICATION COMPLETE - NODE IS READY&lt;/b&gt;',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md148',1,'']]],
  ['issues_46',['Issues',['../md_code__analysis__report.html#autotoc_md47',1,'2.3 Potential Issues'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md312',1,'Critical Compatibility Issues'],['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md12',1,'Fixed Issues'],['../md__t_e_s_t___r_e_s_u_l_t_s.html#autotoc_md469',1,'Known Issues'],['../md_code__analysis__report.html#autotoc_md73',1,'Minor Issues'],['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md13',1,'Pending Issues']]],
  ['issues_20found_47',['5.3 Security Issues Found',['../md_code__analysis__report.html#autotoc_md72',1,'']]],
  ['issues_20resolutions_48',['Build Issues &amp;amp; Resolutions',['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md11',1,'']]],
  ['it_20works_20now_49',['How It Works Now',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md397',1,'']]]
];
