var searchData=
[
  ['n3_20blockchain_20implementation_0',['Neo C++ - Professional Neo N3 Blockchain Implementation',['../md__r_e_a_d_m_e.html',1,'']]],
  ['n3_20c_20implementation_20compatibility_20report_1',['Neo N3 C++ Implementation Compatibility Report',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html',1,'']]],
  ['n3_20compatibility_2',['Neo N3 Compatibility',['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md27',1,'']]],
  ['n3_20protocol_20compatibility_3',['Neo N3 Protocol Compatibility',['../md__v_e_r_i_f_i_c_a_t_i_o_n___c_o_m_p_l_e_t_e.html#autotoc_md509',1,'']]],
  ['n3_20testnet_20compatibility_4',['Neo N3 TestNet Compatibility',['../md__t_e_s_t_n_e_t___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md489',1,'']]],
  ['naming_20convention_5',['Branch Naming Convention',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md138',1,'']]],
  ['native_20contract_20gaps_6',['2. Native Contract Gaps',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md314',1,'']]],
  ['native_20contracts_7',['Native Contracts',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md298',1,'8. Native Contracts'],['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md356',1,'Native Contracts']]],
  ['native_20contracts_20complete_8',['1. &lt;b&gt;Native Contracts - COMPLETE&lt;/b&gt;',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md203',1,'']]],
  ['need_20implementation_9',['Critical Test Modules That Need Implementation',['../md__t_e_s_t___i_m_p_l_e_m_e_n_t_a_t_i_o_n___g_u_i_d_e.html#autotoc_md455',1,'']]],
  ['neo_10',['Benchmarked Improvements (vs C# Neo)',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md214',1,'']]],
  ['neo_20c_11',['Contributing to Neo C++',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['neo_20c_20build_20report_12',['Neo C++ Build Report',['../md__b_u_i_l_d___r_e_p_o_r_t.html',1,'']]],
  ['neo_20c_20code_20analysis_20report_13',['Neo C++ Code Analysis Report',['../md_code__analysis__report.html',1,'']]],
  ['neo_20c_20final_20module_20review_20complete_20c_20compatibility_20analysis_14',['Neo C++ Final Module Review - Complete C# Compatibility Analysis',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html',1,'']]],
  ['neo_20c_20implementation_20final_20delivery_20summary_15',['Neo C++ Implementation - Final Delivery Summary',['../md__f_i_n_a_l___d_e_l_i_v_e_r_y___s_u_m_m_a_r_y.html',1,'']]],
  ['neo_20c_20implementation_20summary_16',['Neo C++ Implementation Summary',['../md__i_m_p_l_e_m_e_n_t_a_t_i_o_n___s_u_m_m_a_r_y.html',1,'']]],
  ['neo_20c_20module_20review_20c_20compatibility_20analysis_17',['Neo C++ Module Review - C# Compatibility Analysis',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html',1,'']]],
  ['neo_20c_20node_20deployment_20guide_18',['Neo C++ Node Deployment Guide',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html',1,'']]],
  ['neo_20c_20node_20final_20verification_20report_19',['Neo C++ Node - Final Verification Report',['../md__v_e_r_i_f_i_c_a_t_i_o_n___c_o_m_p_l_e_t_e.html',1,'']]],
  ['neo_20c_20node_20performance_20optimizations_20',['Neo C++ Node Performance Optimizations',['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html',1,'']]],
  ['neo_20c_20p2p_20synchronization_21',['Final Verification Report - Neo C++ P2P Synchronization',['../md__f_i_n_a_l___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html',1,'']]],
  ['neo_20c_20professional_20neo_20n3_20blockchain_20implementation_22',['Neo C++ - Professional Neo N3 Blockchain Implementation',['../md__r_e_a_d_m_e.html',1,'']]],
  ['neo_20c_20test_20implementation_20guide_23',['Neo C++ Test Implementation Guide',['../md__t_e_s_t___i_m_p_l_e_m_e_n_t_a_t_i_o_n___g_u_i_d_e.html',1,'']]],
  ['neo_20c_20test_20results_20summary_24',['Neo C++ Test Results Summary',['../md__t_e_s_t___r_e_s_u_l_t_s.html',1,'']]],
  ['neo_20c_20testnet_20verification_20report_25',['Neo C++ TestNet Verification Report',['../md__t_e_s_t_n_e_t___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html',1,'']]],
  ['neo_20c_20to_20c_20compatibility_20fixes_20summary_26',['Neo C++ to C# Compatibility Fixes - Summary',['../md__c_o_m_p_a_t_i_b_i_l_i_t_y___f_i_x_e_s___s_u_m_m_a_r_y.html',1,'']]],
  ['neo_20cli_20tool_27',['Neo CLI Tool',['../md__r_e_a_d_m_e.html#autotoc_md434',1,'']]],
  ['neo_20core_20neo_5fsystem_20h_28',['3. &lt;span class=&quot;tt&quot;&gt;include/neo/core/neo_system.h&lt;/span&gt;',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md393',1,'']]],
  ['neo_20n3_20blockchain_20implementation_29',['Neo C++ - Professional Neo N3 Blockchain Implementation',['../md__r_e_a_d_m_e.html',1,'']]],
  ['neo_20n3_20c_20implementation_20compatibility_20report_30',['Neo N3 C++ Implementation Compatibility Report',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html',1,'']]],
  ['neo_20n3_20compatibility_31',['Neo N3 Compatibility',['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md27',1,'']]],
  ['neo_20n3_20protocol_20compatibility_32',['Neo N3 Protocol Compatibility',['../md__v_e_r_i_f_i_c_a_t_i_o_n___c_o_m_p_l_e_t_e.html#autotoc_md509',1,'']]],
  ['neo_20n3_20testnet_20compatibility_33',['Neo N3 TestNet Compatibility',['../md__t_e_s_t_n_e_t___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md489',1,'']]],
  ['neo_20node_34',['Running a Neo Node',['../md__r_e_a_d_m_e.html#autotoc_md433',1,'']]],
  ['neo_20standards_35',['Compliance with Neo Standards',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md228',1,'']]],
  ['neo_20vm_20implementation_36',['Neo VM Implementation',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md354',1,'']]],
  ['neo3transaction_37',['Neo3Transaction',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md340',1,'']]],
  ['neo_3a_3aconsensus_38',['7. Consensus Module (neo::consensus)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md295',1,'']]],
  ['neo_3a_3acryptography_39',['2. Cryptography Module (neo::cryptography)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md279',1,'']]],
  ['neo_3a_3aio_40',['1. IO Module (neo::io)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md275',1,'']]],
  ['neo_3a_3aledger_41',['4. Ledger Module (neo::ledger)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md285',1,'']]],
  ['neo_3a_3anetwork_42',['5. Network Module (neo::network)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md289',1,'']]],
  ['neo_3a_3avm_43',['3. VM Module (neo::vm)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md282',1,'']]],
  ['neo_5fnode_5fproduction_5fready_20cpp_44',['1. &lt;span class=&quot;tt&quot;&gt;apps/neo_node_production_ready.cpp&lt;/span&gt;',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md391',1,'']]],
  ['neo_5fsystem_20cpp_45',['4. &lt;span class=&quot;tt&quot;&gt;src/core/neo_system.cpp&lt;/span&gt;',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md394',1,'']]],
  ['neo_5fsystem_20h_46',['3. &lt;span class=&quot;tt&quot;&gt;include/neo/core/neo_system.h&lt;/span&gt;',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md393',1,'']]],
  ['neosystem_20main_20orchestrator_47',['NeoSystem (Main Orchestrator)',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md337',1,'']]],
  ['nep_2017_20rpc_20methods_20implemented_48',['3. &lt;b&gt;NEP-17 RPC Methods - IMPLEMENTED&lt;/b&gt;',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md205',1,'']]],
  ['nep_20compliance_49',['NEP Compliance',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md229',1,'']]],
  ['network_20✅_50',['3. P2P Network ✅',['../md__v_e_r_i_f_i_c_a_t_i_o_n___c_o_m_p_l_e_t_e.html#autotoc_md501',1,'']]],
  ['network_20capabilities_51',['🌐 &lt;b&gt;Network Capabilities&lt;/b&gt;',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md162',1,'']]],
  ['network_20connection_20✅_52',['1. P2P Network Connection ✅',['../md__t_e_s_t_n_e_t___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md477',1,'']]],
  ['network_20features_53',['Network Features',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md208',1,'2. <b>Advanced Network Features</b>'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md315',1,'3. Advanced Network Features']]],
  ['network_20messages_20tested_54',['Network Messages Tested',['../md__t_e_s_t_n_e_t___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md483',1,'']]],
  ['network_20module_20neo_3a_3anetwork_55',['5. Network Module (neo::network)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md289',1,'']]],
  ['network_20optimizations_56',['4. Network Optimizations',['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html#autotoc_md411',1,'']]],
  ['network_20p2p_20block_5fsync_5fmanager_20cpp_57',['2. &lt;span class=&quot;tt&quot;&gt;src/network/p2p/block_sync_manager.cpp&lt;/span&gt;',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md392',1,'']]],
  ['network_20performance_20metrics_58',['4. Network Performance Metrics',['../md__t_e_s_t_n_e_t___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md480',1,'']]],
  ['network_20protocol_20✅_59',['Network Protocol ✅',['../md_code__analysis__report.html#autotoc_md56',1,'3.3 Network Protocol ✅'],['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md347',1,'6. Network Protocol ✅']]],
  ['new_20integration_20test_20results_60',['New Integration Test Results',['../md__n_e_w___i_n_t_e_g_r_a_t_i_o_n___t_e_s_t___r_e_s_u_l_t_s.html',1,'']]],
  ['next_20steps_61',['Next Steps',['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md22',1,'Next Steps'],['../md_code__analysis__report.html#autotoc_md97',1,'Next Steps'],['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md400',1,'Next Steps'],['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md235',1,'Recommended Next Steps']]],
  ['next_20steps_3a_62',['Next Steps:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md330',1,'']]],
  ['nice_20to_20have_20_3a_63',['Priority 3 (Nice to Have):',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md319',1,'']]],
  ['no_20performance_20anti_20patterns_64',['No Performance Anti-patterns',['../md_code__analysis__report.html#autotoc_md61',1,'']]],
  ['node_65',['Node',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md156',1,'<b>1. Build the Node</b>'],['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md158',1,'<b>3. Start the Node</b>'],['../md__r_e_a_d_m_e.html#autotoc_md433',1,'Running a Neo Node'],['../md__r_e_a_d_m_e.html#autotoc_md435',1,'Test Node']]],
  ['node_20deployment_20guide_66',['Neo C++ Node Deployment Guide',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html',1,'']]],
  ['node_20final_20verification_20report_67',['Neo C++ Node - Final Verification Report',['../md__v_e_r_i_f_i_c_a_t_i_o_n___c_o_m_p_l_e_t_e.html',1,'']]],
  ['node_20functionality_3a_20✅_20100_20operational_68',['&lt;b&gt;Node Functionality: ✅ 100% OPERATIONAL&lt;/b&gt;',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md154',1,'']]],
  ['node_20is_20ready_69',['✅ &lt;b&gt;VERIFICATION COMPLETE - NODE IS READY&lt;/b&gt;',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md148',1,'']]],
  ['node_20management_3a_70',['&lt;b&gt;Node Management:&lt;/b&gt;',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md169',1,'']]],
  ['node_20operational_20status_71',['Node Operational Status',['../md__t_e_s_t_n_e_t___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md485',1,'']]],
  ['node_20performance_20optimizations_72',['Neo C++ Node Performance Optimizations',['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html',1,'']]],
  ['now_73',['How It Works Now',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md397',1,'']]]
];
