var searchData=
[
  ['machine_20✅_0',['9. Virtual Machine ✅',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md353',1,'']]],
  ['machine_20vm_20✅_1',['1. Virtual Machine (VM) ✅',['../md__v_e_r_i_f_i_c_a_t_i_o_n___c_o_m_p_l_e_t_e.html#autotoc_md499',1,'']]],
  ['made_2',['Key Changes Made',['../md__f_i_n_a_l___d_e_l_i_v_e_r_y___s_u_m_m_a_r_y.html#autotoc_md190',1,'']]],
  ['main_20orchestrator_3',['NeoSystem (Main Orchestrator)',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md337',1,'']]],
  ['mainnet_4',['🔧 Recommended Before MainNet',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md227',1,'']]],
  ['mainnet_20configuration_20config_20mainnet_20json_5',['Mainnet Configuration (&lt;span class=&quot;tt&quot;&gt;config/mainnet.json&lt;/span&gt;)',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md396',1,'']]],
  ['mainnet_20json_6',['Mainnet Configuration (&lt;span class=&quot;tt&quot;&gt;config/mainnet.json&lt;/span&gt;)',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md396',1,'']]],
  ['make_20changes_7',['2. Make Changes',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md129',1,'']]],
  ['management_8',['Management',['../md_code__analysis__report.html#autotoc_md37',1,'1.1 Memory Management'],['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html#autotoc_md410',1,'3. Memory Pool Management'],['../md_code__analysis__report.html#autotoc_md79',1,'6.3 Dependency Management']]],
  ['management_20✅_9',['Management ✅',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md345',1,'5. State Management ✅'],['../md__c_o_m_p_a_t_i_b_i_l_i_t_y___f_i_x_e_s___s_u_m_m_a_r_y.html#autotoc_md108',1,'7. PoolItem Transaction Management ✅']]],
  ['management_20comparison_10',['Memory Management Comparison',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md323',1,'']]],
  ['management_3a_11',['&lt;b&gt;Node Management:&lt;/b&gt;',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md169',1,'']]],
  ['manager_12',['7.1 Transaction Pool Manager',['../md_code__analysis__report.html#autotoc_md82',1,'']]],
  ['manager_20thread_20safety_13',['2.2 Transaction Pool Manager Thread Safety',['../md_code__analysis__report.html#autotoc_md46',1,'']]],
  ['match_14',['Perfect Alignment (100% Match)',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md211',1,'']]],
  ['matrix_15',['Module Completeness Matrix',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md200',1,'']]],
  ['mechanism_20✅_16',['4. Consensus Mechanism ✅',['../md__v_e_r_i_f_i_c_a_t_i_o_n___c_o_m_p_l_e_t_e.html#autotoc_md502',1,'']]],
  ['mechanisms_17',['2.1 Synchronization Mechanisms',['../md_code__analysis__report.html#autotoc_md45',1,'']]],
  ['medium_20priority_20🟡_18',['Medium Priority 🟡',['../md_code__analysis__report.html#autotoc_md89',1,'']]],
  ['memory_20efficiency_19',['4.2 Memory Efficiency',['../md_code__analysis__report.html#autotoc_md62',1,'']]],
  ['memory_20management_20',['1.1 Memory Management',['../md_code__analysis__report.html#autotoc_md37',1,'']]],
  ['memory_20management_20comparison_21',['Memory Management Comparison',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md323',1,'']]],
  ['memory_20pool_22',['7.2 Memory Pool',['../md_code__analysis__report.html#autotoc_md85',1,'']]],
  ['memory_20pool_20architecture_20✅_23',['3. Memory Pool Architecture ✅',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md341',1,'']]],
  ['memory_20pool_20enhancement_24',['Memory Pool Enhancement',['../md__c_o_m_p_a_t_i_b_i_l_i_t_y___f_i_x_e_s___s_u_m_m_a_r_y.html#autotoc_md111',1,'']]],
  ['memory_20pool_20management_25',['3. Memory Pool Management',['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html#autotoc_md410',1,'']]],
  ['memory_20pool_20structure_26',['Memory Pool Structure',['../md_code__analysis__report.html#autotoc_md51',1,'']]],
  ['memory_20pool_20usage_27',['Memory Pool Usage',['../md__c_o_m_p_a_t_i_b_i_l_i_t_y___f_i_x_e_s___s_u_m_m_a_r_y.html#autotoc_md120',1,'']]],
  ['memorypool_20architecture_20✅_28',['2. Enhanced MemoryPool Architecture ✅',['../md__c_o_m_p_a_t_i_b_i_l_i_t_y___f_i_x_e_s___s_u_m_m_a_r_y.html#autotoc_md103',1,'']]],
  ['message_20compatibility_29',['P2P Message Compatibility',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md348',1,'']]],
  ['message_20convention_30',['Commit Message Convention',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md137',1,'']]],
  ['messages_20tested_31',['Network Messages Tested',['../md__t_e_s_t_n_e_t___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md483',1,'']]],
  ['method_3a_32',['Method:',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md159',1,'<b>CLI Method:</b>'],['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md160',1,'<b>Direct Method:</b>']]],
  ['methods_33',['Methods',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md209',1,'3. <b>Some RPC Methods</b>'],['../md_code__analysis__report.html#autotoc_md54',1,'Implemented Methods']]],
  ['methods_20compatibility_34',['RPC Methods Compatibility',['../md__n_e_o___n3___c_o_m_p_a_t_i_b_i_l_i_t_y___r_e_p_o_r_t.html#autotoc_md350',1,'']]],
  ['methods_20implemented_35',['3. &lt;b&gt;NEP-17 RPC Methods - IMPLEMENTED&lt;/b&gt;',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md205',1,'']]],
  ['methods_3a_36',['Methods:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md307',1,'Implemented Methods:'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md308',1,'Missing Methods:']]],
  ['metrics_37',['Metrics',['../md__t_e_s_t_n_e_t___v_e_r_i_f_i_c_a_t_i_o_n___r_e_p_o_r_t.html#autotoc_md480',1,'4. Network Performance Metrics'],['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html#autotoc_md415',1,'8. Monitoring and Metrics'],['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md215',1,'Code Quality Metrics'],['../md_code__analysis__report.html#autotoc_md33',1,'Key Metrics'],['../md__b_u_i_l_d___r_e_p_o_r_t.html#autotoc_md14',1,'Performance Metrics'],['../md__v_e_r_i_f_i_c_a_t_i_o_n___c_o_m_p_l_e_t_e.html#autotoc_md507',1,'Success Metrics']]],
  ['minimum_20requirements_3a_38',['&lt;b&gt;Minimum Requirements:&lt;/b&gt;',['../md__d_e_p_l_o_y_m_e_n_t___g_u_i_d_e.html#autotoc_md166',1,'']]],
  ['minor_20deviations_3a_39',['⚠️ Minor Deviations:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md322',1,'']]],
  ['minor_20differences_3a_40',['Minor Differences:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md277',1,'']]],
  ['minor_20gaps_41',['Minor Gaps',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md233',1,'']]],
  ['minor_20gaps_3a_42',['Minor Gaps:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md284',1,'Minor Gaps:'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md291',1,'Minor Gaps:']]],
  ['minor_20issues_43',['Minor Issues',['../md_code__analysis__report.html#autotoc_md73',1,'']]],
  ['minor_20variations_20acceptable_44',['Minor Variations (Acceptable)',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md212',1,'']]],
  ['missing_45',['Missing',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md206',1,'⚠️ ACTUAL GAPS (Confirmed Missing)'],['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md202',1,'✅ CONFIRMED IMPLEMENTATIONS (Previously Thought Missing)']]],
  ['missing_20features_20impact_20analysis_46',['Missing Features Impact Analysis',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md222',1,'']]],
  ['missing_20features_3a_47',['Missing Features:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md287',1,'']]],
  ['missing_20interops_3a_48',['Missing Interops:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md294',1,'']]],
  ['missing_20methods_3a_49',['Missing Methods:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md308',1,'']]],
  ['missing_20official_20plugins_3a_50',['Missing Official Plugins:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md311',1,'']]],
  ['missing_3a_51',['Missing:',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md297',1,'Missing:'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md300',1,'Missing:'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md305',1,'Missing:']]],
  ['mitigated_52',['Already Mitigated',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md224',1,'']]],
  ['modifications_53',['Modifications',['../md__f_i_n_a_l___d_e_l_i_v_e_r_y___s_u_m_m_a_r_y.html#autotoc_md189',1,'Code Modifications'],['../md__i_m_p_l_e_m_e_n_t_a_t_i_o_n___s_u_m_m_a_r_y.html#autotoc_md266',1,'Key Modifications']]],
  ['modified_54',['Key Files Modified',['../md__p2_p___s_y_n_c___c_h_a_n_g_e_s.html#autotoc_md390',1,'']]],
  ['module_55',['Module',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md303',1,'10. Wallets Module'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md306',1,'11. RPC Module'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md309',1,'12. Plugins Module'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md292',1,'6. SmartContract Module'],['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md301',1,'9. Persistence Module']]],
  ['module_20analysis_56',['Detailed Module Analysis',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md274',1,'']]],
  ['module_20completeness_20matrix_57',['Module Completeness Matrix',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md200',1,'']]],
  ['module_20neo_3a_3aconsensus_58',['7. Consensus Module (neo::consensus)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md295',1,'']]],
  ['module_20neo_3a_3acryptography_59',['2. Cryptography Module (neo::cryptography)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md279',1,'']]],
  ['module_20neo_3a_3aio_60',['1. IO Module (neo::io)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md275',1,'']]],
  ['module_20neo_3a_3aledger_61',['4. Ledger Module (neo::ledger)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md285',1,'']]],
  ['module_20neo_3a_3anetwork_62',['5. Network Module (neo::network)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md289',1,'']]],
  ['module_20neo_3a_3avm_63',['3. VM Module (neo::vm)',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md282',1,'']]],
  ['module_20review_20c_20compatibility_20analysis_64',['Neo C++ Module Review - C# Compatibility Analysis',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html',1,'']]],
  ['module_20review_20complete_20c_20compatibility_20analysis_65',['Neo C++ Final Module Review - Complete C# Compatibility Analysis',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html',1,'']]],
  ['module_20status_20summary_66',['Module Status Summary',['../md__m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md273',1,'']]],
  ['module_20structure_67',['6.2 Module Structure',['../md_code__analysis__report.html#autotoc_md78',1,'']]],
  ['modules_68',['Incomplete Test Modules',['../md__t_e_s_t___i_m_p_l_e_m_e_n_t_a_t_i_o_n___g_u_i_d_e.html#autotoc_md456',1,'']]],
  ['modules_20that_20need_20implementation_69',['Critical Test Modules That Need Implementation',['../md__t_e_s_t___i_m_p_l_e_m_e_n_t_a_t_i_o_n___g_u_i_d_e.html#autotoc_md455',1,'']]],
  ['monitoring_20and_20metrics_70',['8. Monitoring and Metrics',['../md__p_e_r_f_o_r_m_a_n_c_e___o_p_t_i_m_i_z_a_t_i_o_n_s.html#autotoc_md415',1,'']]],
  ['mpt_20state_20root_20light_20client_20support_71',['1. &lt;b&gt;MPT State Root (Light Client Support)&lt;/b&gt;',['../md__f_i_n_a_l___m_o_d_u_l_e___r_e_v_i_e_w.html#autotoc_md207',1,'']]]
];
