# Netlify deployment configuration for Neo C++ Website

[build]
  # Build command (if using a static site generator)
  command = "echo 'Static site - no build required'"
  
  # Directory to publish
  publish = "."
  
  # Functions directory (for serverless functions if needed)
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Environment variables
  HUGO_VERSION = "0.110.0"
  HUGO_ENV = "production"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://api.github.com;
      frame-src 'none';
      object-src 'none';
    """

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/docs/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirects for better SEO and user experience
[[redirects]]
  from = "/github"
  to = "https://github.com/r3e-network/neo_cpp"
  status = 302

[[redirects]]
  from = "/releases"
  to = "https://github.com/r3e-network/neo_cpp/releases"
  status = 302

[[redirects]]
  from = "/docs"
  to = "/docs/getting-started.html"
  status = 301

[[redirects]]
  from = "/download"
  to = "/#download"
  status = 301

[[redirects]]
  from = "/api"
  to = "/docs/api-reference.html"
  status = 301

# SPA fallback (if needed for client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Form handling (for contact forms if added later)
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://neo-cpp.netlify.app"

# Performance optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Split testing (A/B testing configuration)
[[splits]]
  id = "hero-cta"
  path = "/"
  branches = [
    {branch = "main", percentage = 100}
  ]

# Edge handlers (for advanced functionality)
[[edge_handlers]]
  handler = "geolocation"
  path = "/api/*"

# Branch deploy context
[context.production]
  command = "echo 'Production build'"
  
[context.deploy-preview]
  command = "echo 'Deploy preview build'"
  
[context.branch-deploy]
  command = "echo 'Branch deploy build'"

# Environment-specific settings
[context.production.environment]
  HUGO_ENV = "production"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "development"
  NODE_ENV = "development"

[context.branch-deploy.environment]
  HUGO_ENV = "development"
  NODE_ENV = "development"